Feature/7
Glaih/TODOEd pull request #10
Opened 2021-02-10 13:27 UTC by Glaih

Resolve #7

2021-02-10 14:56 UTC, titov-rabota requested changes

2021-02-10 14:56 UTC, titov-rabota commented on api/func/registration.py
> +    hashed = bcrypt.hashpw(psw.encode(), salt)
Ты в соседнем PR уже исправляешь этот код.
Не стоит трогать строчки кода, которые не относятся к задаче.
Этим ты породил конфликт, который тебе надо будет исправлять.

2021-02-10 14:56 UTC, titov-rabota commented on api/app.py
> +    auth_request = request.get_json()
Раньше при передаче невалидного json (который функция get_json не может распарсить) ты ловил исключение `TypeError` и возвращал ошибку.

Сейчас твой код просто упадет, это не хорошо.

2021-02-10 14:56 UTC, titov-rabota commented on api/func/registration.py
> +        if Path(DB_PATH).is_file():
У тебя в нескольких местах есть проверка `if Path(DB_PATH).is_file()`.
Давай избавимся от дублирования кода и будем проверять существование базы в одном месте и один раз.
Будет считать, что база не удалится в процессе работы приложения.

2021-02-10 14:56 UTC, titov-rabota commented on api/tests/test_app.py
> +    def test_password_written(self):
Не стоит смешивать разные ветки, потом задолбаешься править конфликты.

2021-02-10 16:57 UTC, Glaih commented on api/app.py
> +    auth_request = request.get_json()
Никак не получается его уронить.

2021-02-10 17:00 UTC, titov-rabota commented on api/app.py
> +    auth_request = request.get_json()
Передай в запросе:
`{"test": "}`

2021-02-10 17:02 UTC, Glaih commented on api/tests/test_app.py
> +    def test_password_written(self):
Resolved.

2021-02-11 07:13 UTC, Glaih commented on api/app.py
> +    auth_request = request.get_json()
`get_json()` сам обрабатывает эту ошибку, я прав?

2021-02-11 08:36 UTC, Glaih commented
Все таки вылез конфликт. Придется руками мержить.

2021-02-11 08:37 UTC, Glaih commented on api/func/registration.py
> +        if Path(DB_PATH).is_file():
Оставил 2 проверки пути. В `registration.py` и в `test_app.py`. В `registration.py` пока нету функции чтения из базы, приходится делать это напрямую из теста  `test_password_written`. Для удобства все тесты работающие непосредственно с базой связал одним тест сьютом.

2021-02-11 08:51 UTC, Glaih commented on api/func/registration.py
> +        if Path(DB_PATH).is_file():
UPD. Пока подожди немного, есть небольшая проблема.

2021-02-11 08:51 UTC, titov-rabota commented on api/app.py
> +    level=10,
Замени, пожалуйста, цифру 10 на именованную константу `logging.DEBUG`

2021-02-11 08:52 UTC, titov-rabota commented on .gitignore
> +*.http
Добавь пустую строку в конец файла

2021-02-11 09:05 UTC, Glaih commented on api/app.py
> +    level=10,
Resolve. 8e9b549

2021-02-11 09:05 UTC, Glaih commented on .gitignore
> +*.http
Resolve. 8e9b549

2021-02-11 09:20 UTC, titov-rabota commented on api/tests/create_db.py
> +    if Path(path).is_file():
`path` у тебя так имеет тип `Path` не надо еще раз приводить к этому типу.

2021-02-11 09:22 UTC, titov-rabota approved these changes

2021-02-11 09:22 UTC, titov-rabota commented
Исправь небольшое замечание по `path`, конфликты и можно мержить

2021-02-11 09:31 UTC, Glaih commented on api/tests/create_db.py
> +    if Path(path).is_file():
Resolved. 9b2238e

2021-02-11 09:43 UTC, Glaih commented on api/tests/create_db.py
> +    if Path(path).is_file():
Resolved.

2021-02-11 09:44 UTC, merged