Reworked `test_not_json` and exception catching.
Glaih/TODOEd pull request #13
Opened 2021-02-12 07:54 UTC by Glaih

+Reworked `test_wrong_json` to test for catching all type errors,
renamed it to `test_type_error`
+Reworked except `TypeError` in app.py to return type of `TypeError`

Werkzeug обрабатывате невалидные `JSON` без краша и выводит свою ошибку. Для других `TypeError` переделал `exception TypeError:` в `app.py`. Также переделал `test_not_json` для проверки данного эксепта.

2021-02-12 07:55 UTC, Glaih commented
+Reworked `test_wrong_json` to test for catching all type errors,
renamed it to `test_type_error`
+Reworked except `TypeError` in app.py to return type of `TypeError`

Werkzeug обрабатывате невалидные `JSON` без краша и выводит свою ошибку. Для других `TypeError` переделал `exception TypeError:` в `app.py`. Также переделал `test_not_json` для проверки данного эксепта.

2021-02-12 09:34 UTC, titov-rabota commented on api/app.py
> +    except TypeError as err:
А по какой причине может произойти `TypeError` внутри `write_in_usr_db`?

2021-02-12 09:37 UTC, titov-rabota requested changes

2021-02-12 09:37 UTC, titov-rabota commented on api/tests/test_app.py
> +        self.assertEqual(next(iter(data)), "type_error")
Это очень очень странный способ проверить наличие ключа в словаре.
Предлагаю так больше не делать.я

Наличие ключа проверяется так `'type_error' in data`.
Конструкция `next(iter())` используется редко, обычно для функционального программирования и лени.

2021-02-12 09:42 UTC, Glaih commented on api/app.py
> +    except TypeError as err:
`write_in_usr_db(auth_request['email'], auth_request['password'])` вот тут я подставляю значения в функцию по ключам. Если там не итерируемый объект, вылетает `TypeError`

2021-02-12 10:12 UTC, Glaih commented on api/tests/test_app.py
> +        self.assertEqual(next(iter(data)), "type_error")
Resolved. 8007086

2021-02-12 10:42 UTC, titov-rabota commented on api/app.py
> +    except TypeError as err:
Что должно быть в запросе, что бы там был не итерируемый объект?

2021-02-12 10:52 UTC, titov-rabota commented on api/app.py
> +    except TypeError as err:
И давай ловить исключения максимально узко. Если ты ожидаешь TypeError в выражении var['t'], то лучше обернуть в try только выражение.

2021-02-12 17:33 UTC, Glaih commented on api/app.py
> +    except TypeError as err:
Resolved. c453b12

2021-02-12 19:34 UTC, titov-rabota approved these changes
Небольшое замечание по организации кода, в остальном lgtm

2021-02-12 19:34 UTC, titov-rabota commented on api/app.py
> +        auth_request['password']
```suggestion
        email = auth_request['email']
        password = auth_request['password']
```

2021-02-12 19:34 UTC, titov-rabota commented on api/app.py
> +        return write_in_usr_db(auth_request['email'], auth_request['password'])
```suggestion
        return write_in_usr_db(email, password)
```

2021-02-12 19:34 UTC, titov-rabota commented on api/app.py
> +        auth_request['password']
Идейно получается так:
мы пытаемся получить из запроса какие-то данные (email, password).
если происходит TypeError, то мы возвращаем текстовую ошибку

2021-02-13 15:41 UTC, Glaih commented on api/app.py
> +        auth_request['password']
Resolve. 2551417

2021-02-13 15:41 UTC, merged