Feature/4
Glaih/TODOEd pull request #18
Opened 2021-02-24 09:16 UTC by Glaih

Resolve #4 Алхимия и миграция.

2021-02-24 10:22 UTC, pavel-cogigate requested changes

2021-02-24 10:22 UTC, pavel-cogigate commented on api/app.py
> +        mail = request.get_json()['email']
`get_json` - это метод, который парсит данные запроса.
Давай не будем им злоупотреблять и будем вызывать его один раз, а не 2.
В данном приложении это не критично, но в целом это довольно порочная практика.

2021-02-24 10:22 UTC, pavel-cogigate commented on api/app.py
>      else:
`else` здесь не нужен, он только добавляет вложенности кода.
А в питоне `Flat is better than nested`

2021-02-24 10:22 UTC, pavel-cogigate commented on api/func/__init__.py
> +    app.config.from_object(BaseConfig())
Предлагаю вынести конфиг в аргементы `create_app`
Т.е. для обычного запуска у тебя будет: `app = create_app(base_config)`
Для тестов: `app = create_app(test_config)`

2021-02-24 10:22 UTC, pavel-cogigate commented on api/func/database.py
> +    def _validation_response(self):
`Validation response` в переводе получается `Ответ валидации (проверки)`. Мне кажется, это немного не соответствует происходящему внутри.

Может быть назовем просто `_validate` или как-то близко по смыслу?

2021-02-24 10:22 UTC, pavel-cogigate commented on api/func/database.py
> +        if User.query.filter_by(mail=self.mail.strip()).first() is not None:
```suggestion
        if User.query.filter_by(mail=self.mail.strip()).first():
```

2021-02-24 10:22 UTC, pavel-cogigate commented on api/func/database.py
> +        if self._validate_mail() is False:
```suggestion
        if not self._validate_mail():
```

2021-02-24 10:22 UTC, pavel-cogigate commented on api/func/database.py
> +        if self._validate_password() is False:
```suggestion
        if not self._validate_password():
```

2021-02-24 10:22 UTC, pavel-cogigate commented on api/func/database.py
> +    def return_error(self):
```suggestion
    def get_errors(self):
```
Мы ведь возвращаем больше одной ошибки за раз.
И принято именоать через `get`

2021-02-24 10:22 UTC, pavel-cogigate commented on api/func/database.py
> +        db.session.add(User(mail=self.mail.strip(), password=password_hashed))
Я вижу, что у тебя в нескольких местах применяется `strip()` к почте пользователя. Это выглядит слишком сложным, рано или поздно ты забудешь его сделать.

Давай делать `email = email.strip()` при получении данных, и создавать пользователя уже с очищенной почтой.

2021-02-24 10:36 UTC, Glaih commented on api/app.py
> +        mail = request.get_json()['email']
Ты предлагаешь по старому сделать: `auth_request = request.get_json()`? Вообще странно, что я поменял на `get_json`.

2021-02-24 10:37 UTC, Glaih commented on api/app.py
>      else:
Resolved.

2021-02-24 10:40 UTC, Glaih commented on api/func/database.py
> +    def _validation_response(self):
Resolved

2021-02-24 10:46 UTC, Glaih commented on api/func/database.py
> +    def _validation_response(self):
Описание ошибки он тоже возвращает, но это скорее дополнительная функция.

2021-02-24 11:08 UTC, titov-rabota commented on api/func/database.py
> +        password_hashed = bcrypt.hashpw(self.password.encode(), bcrypt.gensalt())
Меня смущает строка:
`db.session.add(User(mail=self.mail.strip(), password=password_hashed))`
Мы создаем еще одного пользователя с теми же данными, что и у текущего. Можем ли мы этого избежать?

К примеру мы можем сделать так:
```
class User(db.Model):
    _id = db.Column(...)
    email = db.Column(...)
    password = db.Column(...)
    
    @classmethod
    def create(cls, email, plain_password):
        email = email.strip()
        password  = bcrypt.hashpw(self.password.encode(), bcrypt.gensalt())
        user = cls(email, password)
        return user.save()
    
    def save(self):
        self._validate()
        if self._id is None:
            db.session.add(user)
        else:
            db.session.save(user)
            
        db.session.commit()
        return self

def registration(...):
    email = request_data['email']
    plain_password = request_data['password']
    User.create(email=email, plain_password=plain_password)
```

2021-02-24 11:15 UTC, titov-rabota commented on api/func/database.py
> +        db.session.add(User(mail=self.mail.strip(), password=password_hashed))
Есть альтернативный путь https://github.com/Glaih/TODOEd/pull/18/files#r581868039

2021-02-24 11:19 UTC, titov-rabota commented on api/func/database.py
> +        if User.query.filter_by(mail=self.mail.strip()).first() is not None:
А случайно нет метода `exists`?

2021-02-24 11:56 UTC, Glaih commented on api/app.py
>      else:
Resolved. 14c012d

2021-02-24 11:56 UTC, Glaih commented on api/func/database.py
> +    def _validation_response(self):
Resolved. 14c012d

2021-02-24 11:56 UTC, Glaih commented on api/func/database.py
> +        if User.query.filter_by(mail=self.mail.strip()).first() is not None:
Resolved. 14c012d

2021-02-24 11:56 UTC, Glaih commented on api/func/database.py
> +        if self._validate_mail() is False:
Resolved 14c012d

2021-02-24 11:56 UTC, Glaih commented on api/func/database.py
> +        if self._validate_password() is False:
Resolved. 14c012d

2021-02-24 11:57 UTC, Glaih commented on api/func/database.py
> +    def return_error(self):
Resolved. 14c012d

2021-02-24 11:57 UTC, Glaih commented on api/func/database.py
> +        db.session.add(User(mail=self.mail.strip(), password=password_hashed))
Resolved. 14c012d

2021-02-24 15:57 UTC, Glaih commented on api/func/database.py
> +        if User.query.filter_by(mail=self.mail.strip()).first() is not None:
По `exists` почитаю. вообще есть.

2021-02-25 10:00 UTC, Glaih commented on api/func/database.py
> +        password_hashed = bcrypt.hashpw(self.password.encode(), bcrypt.gensalt())
22b8d9c

На изменение полей в дб поставил заглушку, до разработки соответствующей фичи. Будет нагляднее.

2021-02-25 14:59 UTC, titov-rabota approved these changes
lgtm

2021-02-25 15:48 UTC, merged