Feature/5
Glaih/TODOEd pull request #22
Opened 2021-03-01 10:46 UTC by Glaih

Resolve #5

2021-03-01 13:01 UTC, titov-rabota requested changes

2021-03-01 13:01 UTC, titov-rabota commented on api/tests/test_app.py
Проверь что у созданого пользователя email и password соответстауют данным из запроса. А то вдруг у тебя пользователь с пустыми данными создаётся или пароль в чистом виде

2021-03-01 13:20 UTC, titov-rabota commented on api/tests/test_app.py
> +    def test_protected_route(self):
Нехватает проверки на случай когда неавторизованный пользователь пытается получить доступ

2021-03-01 13:22 UTC, Glaih commented on api/core/blueprints.py
> +@jwt_required(refresh=True)
Указывает на то,  что этот эндплинт принимает рефреш токен,  а возвращает то,  что в ретурне

2021-03-02 08:43 UTC, Glaih commented on api/config.py
> +    JWT_TOKEN_LOCATION = ["json"]
имеешь ввиду, записать сгенерированый токен в таблицу юзер в поле, допустим, "jwt"?

2021-03-02 10:33 UTC, Glaih commented on api/core/blueprints.py
> +jwt = JWTManager()
Думал, что его необходимо создавать в файле ендпоинтов. Не посмотрел, что он там нигде не используется.
Resolved 7b82e2b.

2021-03-02 10:33 UTC, Glaih commented on api/core/blueprints.py
> +    return jsonify(access_token=access_token, refresh_token=refresh_token), 200
Resolved 7b82e2b.

2021-03-02 10:34 UTC, Glaih commented on api/core/blueprints.py
> +        mail = auth_request['email']
Resolved 7b82e2b.

2021-03-02 10:34 UTC, Glaih commented on api/config.py
> +    JWT_SECRET_KEY = 'f7Gt5t7N9HtvF628Q0'
Resolved 7b82e2b.

2021-03-02 10:34 UTC, Glaih commented on api/config.py
> +    JWT_ACCESS_TOKEN_EXPIRES = timedelta(hours=1)
Resolved 7b82e2b

2021-03-02 10:34 UTC, Glaih commented on api/config.py
> +    JWT_REFRESH_TOKEN_EXPIRES = timedelta(days=1)
Resolved 7b82e2b.

2021-03-02 10:35 UTC, Glaih commented on api/tests/test_app.py
> +    def test_protected_route(self):
Resolved 7b82e2b.

2021-03-02 10:41 UTC, Glaih commented on api/tests/test_app.py
![изображение](https://user-images.githubusercontent.com/68474306/109636318-7aa87480-7b5c-11eb-91fb-e3f9136baed2.png)

В этом тесте создается новый пользователь, после чего он находится по полю `email` и происходит сверка пароля с хешем.

2021-03-02 11:03 UTC, Glaih commented on api/tests/test_app.py
> +        if method == 'post':
Resolved d988ca5.
Так намного красивее, сохранил себе в назидание.

2021-03-02 15:12 UTC, Glaih commented on api/core/blueprints.py
> +    if mail != "test@mail.ru" or password != "test":
Resolved a825fb9.

2021-03-02 16:33 UTC, titov-rabota requested changes

2021-03-02 16:33 UTC, titov-rabota commented on api/core/blueprints.py
> +    if not check_errors(auth_request)[0]:
`check_errors` выгдядит не очень хорошо:
1. Ты обращаешься к его результатам по индексам, это скрывает имена переменных и непонятно, какие вообще данные возвращаются. Индексы в коде используются крайне редко, а если используются, то их делают именованными.
2. Ты вызываешь `check_errors` несколько раз. С точки зрения логики это выглядит странно. Зачем нам делать проверку на ошибки еще раз, если мы ее делали только что?
3. Имя метода не соответствует его логике. Это не проверка ошибок, это получение данных: mail, password.

Для читающего твой код, строка `mail, password = check_errors(auth_request)[1:3]` выглядит как черная магия. Предлагаю пока избегать любой магии, старайся делать максимально просто.

2021-03-02 16:33 UTC, titov-rabota commented on api/core/blueprints.py
> +def check_errors(json):
Давай перепишим эту функцию. У нее есть ряд проблем:
1. Ты никогда не получишь `TypeError`
2. Первый элемент результата (булевое значение True/ False) выглядит избыточным.

2021-03-02 16:33 UTC, titov-rabota commented on api/core/blueprints.py
> +        return check_errors(auth_request)
Вместо подобного блока условий лучше писать:

```python
if check_errors(auth_request):
    return .....
    
mail, password = check_errors(auth_request)[1:3]
...
```
Это иллюстрация идеи, данный код никуда писать не надо. Функцию `check_errors` лучше переписать

2021-03-02 16:33 UTC, titov-rabota commented on api/core/database.py
> +            raise VerificationError(errors)
Многовато получилось кода, давай упрощать
```suggestion
    @classmethod
    def is_exists(cls, email, password):
        email = email.strip()
        user = cls.query.filter_by(mail=email).first()
        if not user:
            return False
            
        return checkpw(password.encode(), user.password)
```
И убери `VerificationError`. Я понимаю, что ты хотел сделать по аналогии с `ValidationError`, но это немного разные случаи. `ValidationError` - это комплексная провека и валидация данных (в твоем случае не слишком сложная и проверок не так много, но идейно - это именно комплексная проверка)

`VerificationError` - это проверка одного конкретного случая "есть пользователь в базе или нет". Для одной проверки нет смысла делать новое исключение с полем `errors`

2021-03-02 16:33 UTC, titov-rabota commented on api/tests/test_app.py
> +        data = self.request(self.valid_request, self.login)[1]
Лучше так:
`_, data = self.request(self.valid_request, self.login)`

2021-03-02 16:33 UTC, titov-rabota commented on api/tests/test_app.py
> +        request_refresh = {'refresh_token': f'{data["refresh_token"]}'}
```suggestion
        request_refresh = {'refresh_token': data["refresh_token"]}
```

2021-03-02 16:33 UTC, titov-rabota commented on api/tests/test_app.py
> +        request_access = {'access_token': f'{data["access_token"]}'}
```suggestion
        request_access = {'access_token': data["access_token"]}
```

2021-03-02 16:33 UTC, titov-rabota commented on api/tests/test_app.py
> +        self.assertEqual({'logged_in_as': f'{self.valid_request["email"]}'}, access_data)
```suggestion
        self.assertEqual({'logged_in_as': self.valid_request["email"]}, access_data)
```

2021-03-02 16:33 UTC, titov-rabota commented on api/tests/test_app.py
> +        data = self.request(self.valid_request, self.login)[1]
```suggestion
        _, data = self.request(self.valid_request, self.login)
```

2021-03-02 16:33 UTC, titov-rabota commented on api/tests/test_app.py
> +        request_access = {'access_token': f'{data["access_token"]}'}
```suggestion
        request_access = {'access_token': data["access_token"]}
```

2021-03-02 19:37 UTC, titov-rabota commented on api/tests/test_app.py
> +        data = self.request(self.valid_request, self.login)[1]
Кстати, это своего рода сигнал, что метод возвращает что-то не то, или должен быть разбит на 2 метода. Вероятнее всего тебе не нужно возвращать data. Проверь все ли в порядке с методом.

2021-03-03 07:49 UTC, titov-rabota commented on api/config.py
> +    JWT_TOKEN_LOCATION = ["json"]
А где сейчас хранится токен?

2021-03-03 08:04 UTC, Glaih commented on api/core/database.py
> +            raise VerificationError(errors)
Там две проверки. Есть ли в базу пользователь, и если есть, верен ли его пароль.

2021-03-03 08:22 UTC, Glaih commented on api/core/blueprints.py
> +    if not check_errors(auth_request)[0]:
Resolved a63d334.

2021-03-03 08:22 UTC, Glaih commented on api/core/blueprints.py
> +def check_errors(json):
Resolved a63d334

2021-03-03 08:22 UTC, Glaih commented on api/core/blueprints.py
> +        return check_errors(auth_request)
Resolved a63d334

2021-03-03 08:22 UTC, Glaih commented on api/tests/test_app.py
> +        request_refresh = {'refresh_token': f'{data["refresh_token"]}'}
Resolved a63d334

2021-03-03 08:23 UTC, Glaih commented on api/tests/test_app.py
> +        request_access = {'access_token': f'{data["access_token"]}'}
Resolved a63d334

2021-03-03 08:23 UTC, Glaih commented on api/tests/test_app.py
> +        self.assertEqual({'logged_in_as': f'{self.valid_request["email"]}'}, access_data)
Resolved a63d334

2021-03-03 08:23 UTC, Glaih commented on api/tests/test_app.py
> +        data = self.request(self.valid_request, self.login)[1]
Resolved a63d334

2021-03-03 08:23 UTC, Glaih commented on api/tests/test_app.py
> +        request_access = {'access_token': f'{data["access_token"]}'}
Resolved a63d334

2021-03-03 08:50 UTC, Glaih commented on api/tests/test_app.py
> +        data = self.request(self.valid_request, self.login)[1]
в других кейсах он возвращает `response, data = self.request(request_access, self.protected, 'get')` Тут `response` от первого запроса не нужен, только `data`.

2021-03-03 08:50 UTC, titov-rabota commented on api/core/database.py
> +            raise VerificationError(errors)
Я бы предложил не заморачиваться с 2мя ошибками. Это все-таки API, а не форма веб-интерфейса. Это конечно спорный вопрос, но считают не безопасным писать, что неверен именно пароль, это дает возможность перебора пользователей по email.

2021-03-03 08:52 UTC, Glaih commented on api/tests/test_app.py
> +        data = self.request(self.valid_request, self.login)[1]
Не везде поправил, следующим коммитом исправлю.

2021-03-03 08:54 UTC, Glaih commented on api/tests/test_app.py
> +        data = self.request(self.valid_request, self.login)[1]
Resolved f9777a0.

2021-03-03 08:57 UTC, Glaih commented on api/core/database.py
> +            raise VerificationError(errors)
> но считают не безопасным писать, что неверен именно пароль

Тоже об этом подумал. Но на практике 50 на 50. Можно будет капчу воткнуть при 3х попытках. Или все таки переделаем?

2021-03-03 09:27 UTC, titov-rabota requested changes

2021-03-03 09:27 UTC, titov-rabota commented on api/core/blueprints.py
> +        return error.get_errors(), 401
Давай улучшим обработку ошибку и добавим [error handling](https://flask.palletsprojects.com/en/1.1.x/errorhandling/).

Идея в том, что бы унифицировать ошибки и обрабатывать их в одном месте.
Делаем базовый класс ошибок
```python
class BaseErrors(Exception):
    status_code = 400

    def __init__(self, errors):
        self.errors = errors
        
    def get_errors(self):
        return {'errors': self.errors}
```
При необходимости делаем от него производные классы
```python
class ValidationErrors(BaseErrors):
    pass
 
class PermissionErrors(BaseErrors):
    status_code = 403
 ```
 Примеры использования:
 ```python
 errors = {}
 if email_is_invalid:
     errors['email'] = 'Email is invalid'
     
 if password_is_invalid:
     errros['password'] = 'Password is invalid'
     
 raise ValidationErrors(errors)
 ...
 ...
 if user_doesnt_exists:
     raise PermissionError({'email': 'User doesnt exists'})
     
 if password_is_wrong:
     raise PermissionError({...})
 ```
    
Все ValidationError ты можешь обрабатывать в одном месте (см. ссылку на документацию выше)
```python
if isinstance(exc, BaseErrors):
    return {'errors': exc.get_errors()}, exc.status_code
 
 return exc
 ```

2021-03-03 09:34 UTC, Glaih commented on api/core/blueprints.py
> +    except TypeError as err:
```
request_json = 21
response, data = self.request(request_json, self.login)
self.assertEqual(400, response.status_code)
self.assertTrue('type_error' in data)
```

2021-03-03 09:38 UTC, Glaih commented on api/core/blueprints.py
> +    except TypeError as err:
![изображение](https://user-images.githubusercontent.com/68474306/109785678-6a0c0300-7c1d-11eb-8341-3e67b327823a.png)

2021-03-03 09:43 UTC, Glaih commented on api/core/blueprints.py
> +    except TypeError as err:
![изображение](https://user-images.githubusercontent.com/68474306/109786285-0fbf7200-7c1e-11eb-9c1d-f325c4d38a26.png)

2021-03-03 10:06 UTC, titov-rabota commented on api/core/blueprints.py
> +    except TypeError as err:
Интересно, мне казалось оно должно упасть раньше, при парсинге json

2021-03-03 13:13 UTC, Glaih commented on api/core/blueprints.py
> +        return error.get_errors(), 401
Resolved d4e139e.

2021-03-03 16:08 UTC, titov-rabota commented on api/core/database.py
> +            raise PermissionErrors(errors)
Давай сделаем один метод и сократим кол-во кода.
Кроме этого больше нет смысла возвращать True.

2021-03-03 16:10 UTC, titov-rabota commented
Метод `verify_user` можно улучшить, как по кол-ву кода, так и по читаемости.
В остальном lgtm

2021-03-03 22:53 UTC, titov-rabota commented on api/core/database.py
> +                errors['password'] = 'incorrect password'  # TODO Implement some CAPTCHAlike verification.
Давай писать задачи в issues.
И если и делать, то не капчу а тротлинг или механизм блокировки. Здесь нет веб-интерфейса для капчи, это ведь api

2021-03-04 07:42 UTC, titov-rabota commented on api/config.py
> +    SECRET_KEY = environ.get('SECRET')
Секрет кей не может быть пустым. В данном случае значение None нас не устраивает. Поправь, пожалуйста.

2021-03-04 07:42 UTC, titov-rabota commented on api/config.py
> +    JWT_SECRET_KEY = environ.get('JWT_SECRET')
Так же как и секрет кей не должно быть пустым

2021-03-04 08:12 UTC, Glaih commented on api/core/database.py
> +            raise PermissionErrors(errors)
Resolved 1210412.

2021-03-04 08:12 UTC, Glaih commented on api/core/database.py
> +                errors['password'] = 'incorrect password'  # TODO Implement some CAPTCHAlike verification.
Resolved 1210412.

2021-03-04 09:45 UTC, Glaih commented on api/config.py
> +    SECRET_KEY = environ.get('SECRET')
Resolved 19e4128.

2021-03-04 09:45 UTC, Glaih commented on api/config.py
> +    JWT_SECRET_KEY = environ.get('JWT_SECRET')
Resolved 19e4128.

2021-03-04 14:46 UTC, titov-rabota commented on api/core/database.py
> +        if not User.query.filter_by(mail=email).first():
Незачем делать запрос еще раз.
Давай упростим до:
```suggestion
        if not user:
```

2021-03-04 14:49 UTC, titov-rabota commented on api/core/database.py
> +        if not bool(re.search(r"^[-\w.]+@([A-z0-9][-A-z0-9]+\.)+[A-z]{2,4}$", email)):
Давай скомплируем регулярку и будет использовать компилированную версию.
https://docs.python.org/3/library/re.html#re.compile

2021-03-04 14:50 UTC, titov-rabota commented on api/core/database.py
> +        if not bool(8 <= len(password) <= 30):
Мне кажется должно и так работать
```suggestion
        if not (8 <= len(password) <= 30):
```

2021-03-04 15:21 UTC, Glaih commented on api/core/database.py
> +        if not User.query.filter_by(mail=email).first():
Resolved 8e3a7d2.

2021-03-04 15:22 UTC, Glaih commented on api/core/database.py
> +        if not bool(re.search(r"^[-\w.]+@([A-z0-9][-A-z0-9]+\.)+[A-z]{2,4}$", email)):
Resolved 8e3a7d2.

2021-03-04 15:22 UTC, Glaih commented on api/core/database.py
> +        if not bool(8 <= len(password) <= 30):
Resolved 8e3a7d2.

2021-03-04 16:32 UTC, titov-rabota approved these changes

2021-03-04 17:03 UTC, merged