+Reworked app config to work with PostgreSQL.
Glaih/TODOEd pull request #28
Opened 2021-03-05 21:34 UTC by Glaih

Resolve #27

2021-03-06 10:49 UTC, titov-rabota requested changes

2021-03-06 10:49 UTC, titov-rabota commented on api/config.py
> +    SQLALCHEMY_DATABASE_URI = f'postgresql://{DB_LOGIN}:{DB_PASSWORD}@{DB_HOST}/users'
Давай переименуем имя базы в `todo`
У тебя ведь там не только пользователи.

2021-03-06 10:49 UTC, titov-rabota commented on api/config.py
> +    SQLALCHEMY_DATABASE_URI = f'postgresql://{DB_LOGIN}:{DB_PASSWORD}@{DB_HOST}/test_users'
Здесь соответственно `test_todo`

2021-03-06 10:49 UTC, titov-rabota commented on api/core/blueprints.py
> +    user_id = User.verify_user(mail, password)
И переименуй, пожалуйста `verify_user` в `verify`.
Это метод класса пользователя, получается дублирование.

2021-03-06 10:49 UTC, titov-rabota commented on api/tests/create_db.py
> +class User(db.Model):
А зачем тебе второй класс пользователя?

2021-03-06 10:49 UTC, titov-rabota commented on api/tests/test_app.py
> +        clear_db('test_users')
Давай вынесем имя базы в константу

2021-03-06 10:56 UTC, titov-rabota commented on api/migrations/versions/3324d68d95da_added_column_is_active_to_users_table.py
> +"""Added column is_active to users table
Ниже уже есть файл миграций для добавления `is_active`.
Алхимия генерирует по 2 миграции?

2021-03-06 10:57 UTC, titov-rabota commented on api/tests/clear_db.py
> +            cursor.execute("TRUNCATE users")
Судя по названия метода мы хотим очищать базу целиком.
Если это так, то давай подправим код, что бы чистить все таблицы базы, а не только `users`

2021-03-06 10:58 UTC, titov-rabota commented on api/tests/clear_db.py
> +    clear_db('users')
Предлагаю вынести имя базы в константу

2021-03-06 11:02 UTC, titov-rabota commented on api/tests/test_app.py
> +                conn.commit()
Для низкоуровнего кода есть Алхимия, давай делать запросы через неё.
Добавить в класс `User` новый метод для получения пользователя `User.get(mail)`.

2021-03-06 12:10 UTC, Glaih commented on api/tests/create_db.py
> +class User(db.Model):
Create_db вообще уберу.  Это сугубо для личного пользования, для создания изначальной базы.

2021-03-06 14:29 UTC, Glaih commented on api/core/blueprints.py
> +    user_id = User.verify_user(mail, password)
У меня только один метод класса `User` с именем `verify_user`. Других функций, или методов с таким именем нет.

2021-03-06 14:50 UTC, Glaih commented on api/tests/clear_db.py
> +            cursor.execute("TRUNCATE users")
Самый простой вариант это создать шаблон базы и при необходимости сносить ее и создавать из шаблона:
![image](https://user-images.githubusercontent.com/68474306/110210736-22e37380-7ea4-11eb-8520-ea64d30f08e8.png)

Либо использовать довольно громоздкий скрипт:
![image](https://user-images.githubusercontent.com/68474306/110210785-5920f300-7ea4-11eb-80b0-de2995c3577f.png)


По моему проще руками добавить необходимые таблицы в `clear_db`, тут их не так много будет.

2021-03-06 14:56 UTC, Glaih commented on api/migrations/versions/3324d68d95da_added_column_is_active_to_users_table.py
> +"""Added column is_active to users table
Я так понимаю что 1 - для тестовой базы.

2021-03-06 15:00 UTC, Glaih commented on api/migrations/versions/3324d68d95da_added_column_is_active_to_users_table.py
> +"""Added column is_active to users table
В дальнейшем тестовую базу буду копировать с основной.

2021-03-06 15:30 UTC, Glaih commented on api/tests/test_app.py
> +                conn.commit()
Resolved 836967e.

2021-03-06 15:30 UTC, Glaih commented on api/tests/clear_db.py
> +    clear_db('users')
Resolved 836967e.

2021-03-06 15:30 UTC, Glaih commented on api/tests/test_app.py
> +        clear_db('test_users')
Resolved 836967e.

2021-03-06 15:30 UTC, Glaih commented on api/tests/create_db.py
> +class User(db.Model):
Resolved 836967e.

2021-03-06 15:30 UTC, Glaih commented on api/config.py
> +    SQLALCHEMY_DATABASE_URI = f'postgresql://{DB_LOGIN}:{DB_PASSWORD}@{DB_HOST}/test_users'
Resolved 836967e.

2021-03-06 15:30 UTC, Glaih commented on api/config.py
> +    SQLALCHEMY_DATABASE_URI = f'postgresql://{DB_LOGIN}:{DB_PASSWORD}@{DB_HOST}/users'
Resolved 836967e.

2021-03-06 17:14 UTC, titov-rabota commented on api/tests/clear_db.py
> +            cursor.execute("TRUNCATE users")
А чем плох вариант с шаблоном?
Еще можно сделать дамп в формате sql и восстанавливать из него

2021-03-06 17:23 UTC, titov-rabota requested changes

2021-03-06 17:23 UTC, titov-rabota commented on api/config.py
> +BASE_NAME = 'todo'
Переименую пожалуйста в `DB_NAME` или `DATABASE_NAME`.
У программистов `BASE_NAME` - это базовое имя, а не имя базы.

2021-03-06 17:23 UTC, titov-rabota commented on api/core/blueprints.py
> +    user_id = User.verify_user(mail, password)
У тебя метод `verify_user` находится в классе `User`: `User.verify_user`. Считается излишним писать в имени метода сущность, если она совпадает с классом. Ты ведь не называешь `User.create` как `User.create_user`. Интуитивно и так понятно, что мы создаем пользователя.

2021-03-06 17:24 UTC, titov-rabota commented on api/core/blueprints.py
> +    user_id = User.verify_user(mail, password)
У тебя метод verify_user находится в классе User: User.verify_user. Считается излишним писать в имени метода сущность, если она совпадает с классом. Ты ведь не называешь User.create как User.create_user. Интуитивно и так понятно, что мы создаем пользователя.

2021-03-06 21:05 UTC, Glaih commented on api/core/blueprints.py
> +    user_id = User.verify_user(mail, password)
Логично, поправлю.

2021-03-08 18:39 UTC, Glaih commented on api/tests/clear_db.py
> +            cursor.execute("TRUNCATE users")
Resolved dae7cc8.
В итоге Алхимия и 2 строки кода.

2021-03-08 18:40 UTC, Glaih commented on api/core/blueprints.py
> +    user_id = User.verify_user(mail, password)
Resolved dae7cc8.

2021-03-08 18:40 UTC, Glaih commented on api/config.py
> +BASE_NAME = 'todo'
Resolved dae7cc8.

2021-03-08 19:58 UTC, titov-rabota requested changes

2021-03-08 19:58 UTC, titov-rabota commented on api/core/database.py
> +    def _get_password(cls, email):
С нижним подчёркивание обычно называют приватные методы.
Но ты его вызваешь за пределами класса, что нарушает его приватность. 

И сама идея этого метода довольна спорна. Ты ведь не будешь для получения каждого поля пользователя делать отдельный метод. Давай лучше сделаем метод find или get для получения пользователя и будем брать пароль как user. password

2021-03-08 19:58 UTC, titov-rabota commented on .gitignore
> +notprod
А что такое notprod и поче у он тут дважды?

2021-03-08 20:07 UTC, Glaih commented on .gitignore
> +notprod
Надо будет поправить)  Там инструменты и записи для личного пользования.

2021-03-08 20:28 UTC, Glaih commented on api/core/database.py
> +    def _get_password(cls, email):
Resolved 578e3b2.

2021-03-08 20:28 UTC, Glaih commented on .gitignore
> +notprod
Resolved 578e3b2.

2021-03-09 06:41 UTC, titov-rabota commented on .gitignore
> +notprod
Создай отдельную репу для инструментов и записей. Или пиши в wiki

2021-03-09 07:46 UTC, titov-rabota approved these changes
Небольшое замечание, в остальном норм

2021-03-09 07:46 UTC, titov-rabota commented
И не забудь исправить конфликт

2021-03-09 13:12 UTC, merged